In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

df = pd.DataFrame({'a': a, 'b': b})
df

a   b
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [6]:
np.linspace(-2,2,num=5)

array([-2., -1.,  0.,  1.,  2.])

In [7]:
X=np.array([[1,0],[0,1]]) 

Y=np.array([[2,1],[1,2]]) 

Z=np.dot(X,Y) 
Z

array([[2, 1],
       [1, 2]])

In [9]:
X=np.array([[1,0,1],[2,2,2]]) 

out=X[0:2,2]
out

array([1, 2])

In [10]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a+b 

array([1, 1, 1, 1, 1])

In [11]:
a=np.array([1,1,1,1,1]) 

a+10

array([11, 11, 11, 11, 11])